export { PreferencesProvider } from './ui/preferences-provider'
export { usePreferences } from './model/preferences-context'
export { languages, defaultPreferences, parsePreferences } from './domain/preferences'
export type { Language, ThemeName, Preferences } from './domain/preferences'
export type { PreferencesStorePort } from './domain/preferences-store.port'
export { browserPreferencesStore } from './infrastructure/browser-preferences.store'
